
package test;

import Aritmetica.Aritmetica;
public class tesExepciones {
    public static void main(String[] args) {
        int resultado = 0;
        System.out.println("resultado = "+ resultado);{
        try{
            resultado = division(10,2);
    }catch(OperacionException e ){
                System.out.println("Ocurrio un error de tipo OperacionExeption");
                System.out.println(e.getMessage());
    }
                System.out.println("Ocurrio un error");
                 e.printStackTrace(System.out);//se conoce como la pila de las ecxepciones
                 System.out.println(exeptiones.getMessage());                   
                 }
                 System.out.println("La variable de resultado tiene como valor :"+ resultado);
        
   }
    finally{
            System.out.println("Se reviso la division entre cero");
        {
             
            }  {
            }
    }
}
